# Generated by Django 6.0.2 on 2026-02-22 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.CharField(max_length=400)),
                ('help_text', models.CharField(blank=True, max_length=400)),
                ('qtype', models.CharField(choices=[('YEAR_4', 'Year (4-digit)'), ('RADIO_0_5', 'Radio (0..5)')], max_length=32)),
                ('required', models.BooleanField(default=True)),
                ('db_field', models.SlugField(max_length=64)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formbuilder.form')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('depressed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='formbuilder.form')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='formbuilder.question')),
            ],
            options={
                'ordering': ['value'],
                'unique_together': {('question', 'value')},
            },
        ),
    ]
